// © tamth_
// @version=5
indicator(title='Advanced Ichimoku', shorttitle='Advanced Ichimoku', overlay=true)


var color white_color = color.white
var color blue_color = color.blue
var color purple_color = color.purple
var color yellow_color = color.yellow
var color orange_color = color.orange
var color aqua_color = color.aqua
var color green_color = color.teal
var color red_color = color.red


// Ichimoku
method get_middle_point(int timeframes) => math.avg(ta.lowest(timeframes), ta.highest(timeframes))
method get_future_point(int timeframes, int idx) => math.avg(ta.highest(timeframes - idx), ta.lowest(timeframes - idx))
method get_future_point_1(int timeframes) => get_future_point(timeframes, 1)
method get_future_point_2(int timeframes) => get_future_point(timeframes, 2)
method get_future_point_3(int timeframes) => get_future_point(timeframes, 3)
method get_future_point_4(int timeframes) => get_future_point(timeframes, 4)
method get_future_point_5(int timeframes) => get_future_point(timeframes, 5)
method get_future_point_6(int timeframes) => get_future_point(timeframes, 6)
method get_future_point_7(int timeframes) => get_future_point(timeframes, 7)
method get_future_point_8(int timeframes) => get_future_point(timeframes, 8)
method get_future_point_9(int timeframes) => get_future_point(timeframes, 9)
method get_future_point_10(int timeframes) => get_future_point(timeframes, 10)
method get_future_point_11(int timeframes) => get_future_point(timeframes, 11)
method get_future_point_12(int timeframes) => get_future_point(timeframes, 12)
method get_future_point_13(int timeframes) => get_future_point(timeframes, 13)
method get_future_point_14(int timeframes) => get_future_point(timeframes, 14)
method get_future_point_15(int timeframes) => get_future_point(timeframes, 15)
method get_future_point_16(int timeframes) => get_future_point(timeframes, 16)
method get_future_point_17(int timeframes) => get_future_point(timeframes, 17)
method get_future_point_18(int timeframes) => get_future_point(timeframes, 18)
method get_future_point_19(int timeframes) => get_future_point(timeframes, 19)
method get_future_point_20(int timeframes) => get_future_point(timeframes, 20)
method get_future_point_21(int timeframes) => get_future_point(timeframes, 21)
method get_future_point_22(int timeframes) => get_future_point(timeframes, 22)
method get_future_point_23(int timeframes) => get_future_point(timeframes, 23)
method get_future_point_24(int timeframes) => get_future_point(timeframes, 24)
method get_future_point_25(int timeframes) => get_future_point(timeframes, 25)
method get_future_point_26(int timeframes) => get_future_point(timeframes, 26)

var string tenkan_sen_txt = 'Tenkan-sen'
var string kijun_sen_txt = 'Kijun-sen'
var string short_blade_txt = 'Short Blade'
var string medium_blade_txt = 'Medium Blade'
var string long_blade_txt = 'Long Blade'
var string chikou_span_txt = 'Chikou-span'
var string senkou_span_a_txt = 'Senkou-span A'
var string senkou_span_b_txt = 'Senkou-span B'
var string kumo_cloud_txt = 'Kumo Cloud'
int tenkan_sen_timeframes = input.int(9, minval=1, title=tenkan_sen_txt)
// int short_blade_timeframes = input.int(17, minval=1, title=short_blade_txt)
int kijun_sen_timeframes = input.int(26, minval=1, title=kijun_sen_txt)
int senkou_span_b_timeframes = input.int(52, minval=1, title=senkou_span_b_txt)
int medium_blade_timeframes = input.int(65, minval=1, title=medium_blade_txt)
int long_blade_timeframes = input.int(129, minval=1, title=long_blade_txt)

float tenkan_sen = get_middle_point(tenkan_sen_timeframes)
// float short_blade = get_middle_point(short_blade_timeframes)
float kijun_sen = get_middle_point(kijun_sen_timeframes)
float medium_blade = get_middle_point(medium_blade_timeframes)
float long_blade = get_middle_point(long_blade_timeframes)
float senkou_span_a = math.avg(tenkan_sen, kijun_sen)
float senkou_span_b = get_middle_point(senkou_span_b_timeframes)
plot(close, offset=-25, color=aqua_color, title=chikou_span_txt, linewidth=1)
var senkou_plot_a = plot(senkou_span_a, offset=25, color=green_color, linewidth=1, title=senkou_span_a_txt)
var senkou_plot_b = plot(senkou_span_b, offset=25, color=red_color, linewidth=1, title=senkou_span_b_txt)
fill(senkou_plot_a, senkou_plot_b, color=senkou_span_a > senkou_span_b ? color.new(#52A895, 90) : color.new(#DA4F7A, 90), title=kumo_cloud_txt)
plot(long_blade, color=orange_color, title=long_blade_txt, linewidth=2)
plot(medium_blade, color=yellow_color, title=medium_blade_txt, linewidth=2)
plot(kijun_sen, color=purple_color, title=kijun_sen_txt, linewidth=1)
// plot(short_blade, color=aqua_color, title=short_blade_txt, linewidth=1)
plot(tenkan_sen, color=blue_color, title=tenkan_sen_txt, linewidth=1)

float long_blade_future_point_1 = get_future_point_1(long_blade_timeframes)
float long_blade_future_point_2 = get_future_point_2(long_blade_timeframes)
float long_blade_future_point_3 = get_future_point_3(long_blade_timeframes)
float long_blade_future_point_4 = get_future_point_4(long_blade_timeframes)
float long_blade_future_point_5 = get_future_point_5(long_blade_timeframes)
float long_blade_future_point_6 = get_future_point_6(long_blade_timeframes)
float long_blade_future_point_7 = get_future_point_7(long_blade_timeframes)
float long_blade_future_point_8 = get_future_point_8(long_blade_timeframes)
float long_blade_future_point_9 = get_future_point_9(long_blade_timeframes)
float long_blade_future_point_10 = get_future_point_10(long_blade_timeframes)
float long_blade_future_point_11 = get_future_point_11(long_blade_timeframes)
float long_blade_future_point_12 = get_future_point_12(long_blade_timeframes)
float long_blade_future_point_13 = get_future_point_13(long_blade_timeframes)
float long_blade_future_point_14 = get_future_point_14(long_blade_timeframes)
float long_blade_future_point_15 = get_future_point_15(long_blade_timeframes)
plot(long_blade_future_point_1, title='Long Blade Future Point 1', color=orange_color, linewidth=1, offset=1, show_last=1, style=plot.style_circles, display = display.pane)
plot(long_blade_future_point_2, title='Long Blade Future Point 2', color=orange_color, linewidth=1, offset=2, show_last=1, style=plot.style_circles, display = display.pane)
plot(long_blade_future_point_3, title='Long Blade Future Point 3', color=orange_color, linewidth=1, offset=3, show_last=1, style=plot.style_circles, display = display.pane)
plot(long_blade_future_point_4, title='Long Blade Future Point 4', color=orange_color, linewidth=1, offset=4, show_last=1, style=plot.style_circles, display = display.pane)
plot(long_blade_future_point_5, title='Long Blade Future Point 5', color=orange_color, linewidth=1, offset=5, show_last=1, style=plot.style_circles, display = display.pane)
plot(long_blade_future_point_6, title='Long Blade Future Point 6', color=orange_color, linewidth=1, offset=6, show_last=1, style=plot.style_circles, display = display.pane)
plot(long_blade_future_point_7, title='Long Blade Future Point 7', color=orange_color, linewidth=1, offset=7, show_last=1, style=plot.style_circles, display = display.pane)
plot(long_blade_future_point_8, title='Long Blade Future Point 8', color=orange_color, linewidth=1, offset=8, show_last=1, style=plot.style_circles, display = display.pane)
plot(long_blade_future_point_9, title='Long Blade Future Point 9', color=orange_color, linewidth=1, offset=9, show_last=1, style=plot.style_circles, display = display.pane)
plot(long_blade_future_point_10, title='Long Blade Future Point 10', color=orange_color, linewidth=1, offset=10, show_last=1, style=plot.style_circles, display = display.pane)
plot(long_blade_future_point_11, title='Long Blade Future Point 11', color=orange_color, linewidth=1, offset=11, show_last=1, style=plot.style_circles, display = display.pane)
plot(long_blade_future_point_12, title='Long Blade Future Point 12', color=orange_color, linewidth=1, offset=12, show_last=1, style=plot.style_circles, display = display.pane)
plot(long_blade_future_point_13, title='Long Blade Future Point 13', color=orange_color, linewidth=1, offset=13, show_last=1, style=plot.style_circles, display = display.pane)
plot(long_blade_future_point_14, title='Long Blade Future Point 14', color=orange_color, linewidth=1, offset=14, show_last=1, style=plot.style_circles, display = display.pane)
plot(long_blade_future_point_15, title='Long Blade Future Point 15', color=orange_color, linewidth=1, offset=15, show_last=1, style=plot.style_circles, display = display.pane)

float medium_blade_future_point_1 = get_future_point_1(medium_blade_timeframes)
float medium_blade_future_point_2 = get_future_point_2(medium_blade_timeframes)
float medium_blade_future_point_3 = get_future_point_3(medium_blade_timeframes)
float medium_blade_future_point_4 = get_future_point_4(medium_blade_timeframes)
float medium_blade_future_point_5 = get_future_point_5(medium_blade_timeframes)
float medium_blade_future_point_6 = get_future_point_6(medium_blade_timeframes)
float medium_blade_future_point_7 = get_future_point_7(medium_blade_timeframes)
float medium_blade_future_point_8 = get_future_point_8(medium_blade_timeframes)
float medium_blade_future_point_9 = get_future_point_9(medium_blade_timeframes)
float medium_blade_future_point_10 = get_future_point_10(medium_blade_timeframes)
float medium_blade_future_point_11 = get_future_point_11(medium_blade_timeframes)
float medium_blade_future_point_12 = get_future_point_12(medium_blade_timeframes)
float medium_blade_future_point_13 = get_future_point_13(medium_blade_timeframes)
float medium_blade_future_point_14 = get_future_point_14(medium_blade_timeframes)
float medium_blade_future_point_15 = get_future_point_15(medium_blade_timeframes)
float medium_blade_future_point_16 = get_future_point_16(medium_blade_timeframes)
plot(medium_blade_future_point_1, title='Medium Blade Future Point 1', color=yellow_color, linewidth=1, offset=1, show_last=1, style=plot.style_circles, display = display.pane)
plot(medium_blade_future_point_2, title='Medium Blade Future Point 2', color=yellow_color, linewidth=1, offset=2, show_last=1, style=plot.style_circles, display = display.pane)
plot(medium_blade_future_point_3, title='Medium Blade Future Point 3', color=yellow_color, linewidth=1, offset=3, show_last=1, style=plot.style_circles, display = display.pane)
plot(medium_blade_future_point_4, title='Medium Blade Future Point 4', color=yellow_color, linewidth=1, offset=4, show_last=1, style=plot.style_circles, display = display.pane)
plot(medium_blade_future_point_5, title='Medium Blade Future Point 5', color=yellow_color, linewidth=1, offset=5, show_last=1, style=plot.style_circles, display = display.pane)
plot(medium_blade_future_point_6, title='Medium Blade Future Point 6', color=yellow_color, linewidth=1, offset=6, show_last=1, style=plot.style_circles, display = display.pane)
plot(medium_blade_future_point_7, title='Medium Blade Future Point 7', color=yellow_color, linewidth=1, offset=7, show_last=1, style=plot.style_circles, display = display.pane)
plot(medium_blade_future_point_8, title='Medium Blade Future Point 8', color=yellow_color, linewidth=1, offset=8, show_last=1, style=plot.style_circles, display = display.pane)
plot(medium_blade_future_point_9, title='Medium Blade Future Point 9', color=yellow_color, linewidth=1, offset=9, show_last=1, style=plot.style_circles, display = display.pane)
plot(medium_blade_future_point_10, title='Medium Blade Future Point 10', color=yellow_color, linewidth=1, offset=10, show_last=1, style=plot.style_circles, display = display.pane)
plot(medium_blade_future_point_11, title='Medium Blade Future Point 11', color=yellow_color, linewidth=1, offset=11, show_last=1, style=plot.style_circles, display = display.pane)
plot(medium_blade_future_point_12, title='Medium Blade Future Point 12', color=yellow_color, linewidth=1, offset=12, show_last=1, style=plot.style_circles, display = display.pane)
plot(medium_blade_future_point_13, title='Medium Blade Future Point 13', color=yellow_color, linewidth=1, offset=13, show_last=1, style=plot.style_circles, display = display.pane)
plot(medium_blade_future_point_14, title='Medium Blade Future Point 14', color=yellow_color, linewidth=1, offset=14, show_last=1, style=plot.style_circles, display = display.pane)
plot(medium_blade_future_point_15, title='Medium Blade Future Point 15', color=yellow_color, linewidth=1, offset=15, show_last=1, style=plot.style_circles, display = display.pane)

float kijun_sen_future_point_1 = get_future_point_1(kijun_sen_timeframes)
float kijun_sen_future_point_2 = get_future_point_2(kijun_sen_timeframes)
float kijun_sen_future_point_3 = get_future_point_3(kijun_sen_timeframes)
float kijun_sen_future_point_4 = get_future_point_4(kijun_sen_timeframes)
float kijun_sen_future_point_5 = get_future_point_5(kijun_sen_timeframes)
float kijun_sen_future_point_6 = get_future_point_6(kijun_sen_timeframes)
float kijun_sen_future_point_7 = get_future_point_7(kijun_sen_timeframes)
float kijun_sen_future_point_8 = get_future_point_8(kijun_sen_timeframes)
float kijun_sen_future_point_9 = get_future_point_9(kijun_sen_timeframes)
float kijun_sen_future_point_10 = get_future_point_10(kijun_sen_timeframes)
float kijun_sen_future_point_11 = get_future_point_11(kijun_sen_timeframes)
float kijun_sen_future_point_12 = get_future_point_12(kijun_sen_timeframes)
float kijun_sen_future_point_13 = get_future_point_13(kijun_sen_timeframes)
float kijun_sen_future_point_14 = get_future_point_14(kijun_sen_timeframes)
float kijun_sen_future_point_15 = get_future_point_15(kijun_sen_timeframes)
float kijun_sen_future_point_16 = get_future_point_16(kijun_sen_timeframes)
plot(kijun_sen_future_point_1, title='Kijun-sen Future Point 1', color=purple_color, linewidth=1, offset=1, show_last=1, style=plot.style_circles, display = display.pane)
plot(kijun_sen_future_point_2, title='Kijun-sen Future Point 2', color=purple_color, linewidth=1, offset=2, show_last=1, style=plot.style_circles, display = display.pane)
plot(kijun_sen_future_point_3, title='Kijun-sen Future Point 3', color=purple_color, linewidth=1, offset=3, show_last=1, style=plot.style_circles, display = display.pane)
plot(kijun_sen_future_point_4, title='Kijun-sen Future Point 4', color=purple_color, linewidth=1, offset=4, show_last=1, style=plot.style_circles, display = display.pane)
plot(kijun_sen_future_point_5, title='Kijun-sen Future Point 5', color=purple_color, linewidth=1, offset=5, show_last=1, style=plot.style_circles, display = display.pane)
plot(kijun_sen_future_point_6, title='Kijun-sen Future Point 6', color=purple_color, linewidth=1, offset=6, show_last=1, style=plot.style_circles, display = display.pane)
plot(kijun_sen_future_point_7, title='Kijun-sen Future Point 7', color=purple_color, linewidth=1, offset=7, show_last=1, style=plot.style_circles, display = display.pane)
plot(kijun_sen_future_point_8, title='Kijun-sen Future Point 8', color=purple_color, linewidth=1, offset=8, show_last=1, style=plot.style_circles, display = display.pane)
plot(kijun_sen_future_point_9, title='Kijun-sen Future Point 9', color=purple_color, linewidth=1, offset=9, show_last=1, style=plot.style_circles, display = display.pane)
plot(kijun_sen_future_point_10, title='Kijun-sen Future Point 10', color=purple_color, linewidth=1, offset=10, show_last=1, style=plot.style_circles, display = display.pane)
plot(kijun_sen_future_point_11, title='Kijun-sen Future Point 11', color=purple_color, linewidth=1, offset=11, show_last=1, style=plot.style_circles, display = display.pane)
plot(kijun_sen_future_point_12, title='Kijun-sen Future Point 12', color=purple_color, linewidth=1, offset=12, show_last=1, style=plot.style_circles, display = display.pane)
plot(kijun_sen_future_point_13, title='Kijun-sen Future Point 13', color=purple_color, linewidth=1, offset=13, show_last=1, style=plot.style_circles, display = display.pane)
plot(kijun_sen_future_point_14, title='Kijun-sen Future Point 14', color=purple_color, linewidth=1, offset=14, show_last=1, style=plot.style_circles, display = display.pane)
plot(kijun_sen_future_point_15, title='Kijun-sen Future Point 15', color=purple_color, linewidth=1, offset=15, show_last=1, style=plot.style_circles, display = display.pane)
plot(kijun_sen_future_point_16, title='Kijun-sen Future Point 16', color=purple_color, linewidth=1, offset=16, show_last=1, style=plot.style_circles, display = display.pane)

// float short_blade_future_point_1 = get_future_point_1(short_blade_timeframes)
// float short_blade_future_point_2 = get_future_point_2(short_blade_timeframes)
// float short_blade_future_point_3 = get_future_point_3(short_blade_timeframes)
// float short_blade_future_point_4 = get_future_point_4(short_blade_timeframes)
// float short_blade_future_point_5 = get_future_point_5(short_blade_timeframes)
// float short_blade_future_point_6 = get_future_point_6(short_blade_timeframes)
// float short_blade_future_point_7 = get_future_point_7(short_blade_timeframes)
// float short_blade_future_point_8 = get_future_point_8(short_blade_timeframes)
// float short_blade_future_point_9 = get_future_point_9(short_blade_timeframes)
// float short_blade_future_point_10 = get_future_point_10(short_blade_timeframes)
// float short_blade_future_point_11 = get_future_point_11(short_blade_timeframes)
// float short_blade_future_point_12 = get_future_point_12(short_blade_timeframes)
// float short_blade_future_point_13 = get_future_point_13(short_blade_timeframes)
// float short_blade_future_point_14 = get_future_point_14(short_blade_timeframes)
// float short_blade_future_point_15 = get_future_point_15(short_blade_timeframes)
// float short_blade_future_point_16 = get_future_point_16(short_blade_timeframes)
// plot(short_blade_future_point_1, title='Short Blade Future Point 1', color=aqua_color, linewidth=1, offset=1, show_last=1, style=plot.style_circles, display = display.pane)
// plot(short_blade_future_point_2, title='Short Blade Future Point 2', color=aqua_color, linewidth=1, offset=2, show_last=1, style=plot.style_circles, display = display.pane)
// plot(short_blade_future_point_3, title='Short Blade Future Point 3', color=aqua_color, linewidth=1, offset=3, show_last=1, style=plot.style_circles, display = display.pane)
// plot(short_blade_future_point_4, title='Short Blade Future Point 4', color=aqua_color, linewidth=1, offset=4, show_last=1, style=plot.style_circles, display = display.pane)
// plot(short_blade_future_point_5, title='Short Blade Future Point 5', color=aqua_color, linewidth=1, offset=5, show_last=1, style=plot.style_circles, display = display.pane)
// plot(short_blade_future_point_6, title='Short Blade Future Point 6', color=aqua_color, linewidth=1, offset=6, show_last=1, style=plot.style_circles, display = display.pane)
// plot(short_blade_future_point_7, title='Short Blade Future Point 7', color=aqua_color, linewidth=1, offset=7, show_last=1, style=plot.style_circles, display = display.pane)
// plot(short_blade_future_point_8, title='Short Blade Future Point 8', color=aqua_color, linewidth=1, offset=8, show_last=1, style=plot.style_circles, display = display.pane)
// plot(short_blade_future_point_9, title='Short Blade Future Point 9', color=aqua_color, linewidth=1, offset=9, show_last=1, style=plot.style_circles, display = display.pane)
// plot(short_blade_future_point_10, title='Short Blade Future Point 10', color=aqua_color, linewidth=1, offset=10, show_last=1, style=plot.style_circles, display = display.pane)
// plot(short_blade_future_point_11, title='Short Blade Future Point 11', color=aqua_color, linewidth=1, offset=11, show_last=1, style=plot.style_circles, display = display.pane)
// plot(short_blade_future_point_12, title='Short Blade Future Point 12', color=aqua_color, linewidth=1, offset=12, show_last=1, style=plot.style_circles, display = display.pane)
// plot(short_blade_future_point_13, title='Short Blade Future Point 13', color=aqua_color, linewidth=1, offset=13, show_last=1, style=plot.style_circles, display = display.pane)
// plot(short_blade_future_point_14, title='Short Blade Future Point 14', color=aqua_color, linewidth=1, offset=14, show_last=1, style=plot.style_circles, display = display.pane)
// plot(short_blade_future_point_15, title='Short Blade Future Point 15', color=aqua_color, linewidth=1, offset=15, show_last=1, style=plot.style_circles, display = display.pane)    

float tenkan_sen_future_point_1 = get_future_point_1(tenkan_sen_timeframes)
float tenkan_sen_future_point_2 = get_future_point_2(tenkan_sen_timeframes)
float tenkan_sen_future_point_3 = get_future_point_3(tenkan_sen_timeframes)
float tenkan_sen_future_point_4 = get_future_point_4(tenkan_sen_timeframes)
float tenkan_sen_future_point_5 = get_future_point_5(tenkan_sen_timeframes)
float tenkan_sen_future_point_6 = get_future_point_6(tenkan_sen_timeframes)
float tenkan_sen_future_point_7 = get_future_point_7(tenkan_sen_timeframes)
float tenkan_sen_future_point_8 = get_future_point_8(tenkan_sen_timeframes)
plot(tenkan_sen_future_point_1, title='Tenkan-sen Future Point 1', color=blue_color, linewidth=1, offset=1, show_last=1, style=plot.style_circles, display = display.pane)
plot(tenkan_sen_future_point_2, title='Tenkan-sen Future Point 2', color=blue_color, linewidth=1, offset=2, show_last=1, style=plot.style_circles, display = display.pane)
plot(tenkan_sen_future_point_3, title='Tenkan-sen Future Point 3', color=blue_color, linewidth=1, offset=3, show_last=1, style=plot.style_circles, display = display.pane)
plot(tenkan_sen_future_point_4, title='Tenkan-sen Future Point 4', color=blue_color, linewidth=1, offset=4, show_last=1, style=plot.style_circles, display = display.pane)
plot(tenkan_sen_future_point_5, title='Tenkan-sen Future Point 5', color=blue_color, linewidth=1, offset=5, show_last=1, style=plot.style_circles, display = display.pane)
plot(tenkan_sen_future_point_6, title='Tenkan-sen Future Point 6', color=blue_color, linewidth=1, offset=6, show_last=1, style=plot.style_circles, display = display.pane)
plot(tenkan_sen_future_point_7, title='Tenkan-sen Future Point 7', color=blue_color, linewidth=1, offset=7, show_last=1, style=plot.style_circles, display = display.pane)
plot(tenkan_sen_future_point_8, title='Tenkan-sen Future Point 8', color=blue_color, linewidth=1, offset=8, show_last=1, style=plot.style_circles, display = display.pane)





// Williams Fractals
int fractals_timeframes = input.int(title="Williams Fractals Timeframes", defval=4, minval=2)

// Up Fractals
bool up_flag_down_frontier = true
bool up_flag_up_frontier_0 = true
bool up_flag_up_frontier_2 = true
bool up_flag_up_frontier_3 = true
bool up_flag_up_frontier_4 = true

for idx = 1 to fractals_timeframes
    up_flag_down_frontier := up_flag_down_frontier and (high[fractals_timeframes-idx] < high[fractals_timeframes])
    up_flag_up_frontier_0 := up_flag_up_frontier_0 and (high[fractals_timeframes+idx] < high[fractals_timeframes])
    up_flag_up_frontier_2 := up_flag_up_frontier_2 and (high[fractals_timeframes+1] <= high[fractals_timeframes] and high[fractals_timeframes+idx + 1] < high[fractals_timeframes])
    up_flag_up_frontier_3 := up_flag_up_frontier_3 and (high[fractals_timeframes+1] <= high[fractals_timeframes] and high[fractals_timeframes+2] <= high[fractals_timeframes] and high[fractals_timeframes+idx + 2] < high[fractals_timeframes])
    up_flag_up_frontier_3 := up_flag_up_frontier_3 and (high[fractals_timeframes+1] <= high[fractals_timeframes] and high[fractals_timeframes+2] <= high[fractals_timeframes] and high[fractals_timeframes+3] <= high[fractals_timeframes] and high[fractals_timeframes+idx + 3] < high[fractals_timeframes])
    up_flag_up_frontier_4 := up_flag_up_frontier_4 and (high[fractals_timeframes+1] <= high[fractals_timeframes] and high[fractals_timeframes+2] <= high[fractals_timeframes] and high[fractals_timeframes+3] <= high[fractals_timeframes] and high[fractals_timeframes+4] <= high[fractals_timeframes] and high[fractals_timeframes+idx + 4] < high[fractals_timeframes])

bool flag_up_frontier = up_flag_up_frontier_0 or up_flag_up_frontier_2 or up_flag_up_frontier_3 or up_flag_up_frontier_3 or up_flag_up_frontier_4
bool up_fractal = up_flag_down_frontier and flag_up_frontier

// Down Fractals
bool down_flag_down_frontier = true
bool down_flag_up_frontier_0 = true
bool down_flag_up_frontier_1 = true
bool down_flag_up_frontier_2 = true
bool down_flag_up_frontier_3 = true
bool down_flag_up_frontier_4 = true

for idx = 1 to fractals_timeframes
    down_flag_down_frontier := down_flag_down_frontier and (low[fractals_timeframes-idx] > low[fractals_timeframes])
    down_flag_up_frontier_0 := down_flag_up_frontier_0 and (low[fractals_timeframes+idx] > low[fractals_timeframes])
    down_flag_up_frontier_1 := down_flag_up_frontier_1 and (low[fractals_timeframes+1] >= low[fractals_timeframes] and low[fractals_timeframes+idx + 1] > low[fractals_timeframes])
    down_flag_up_frontier_2 := down_flag_up_frontier_2 and (low[fractals_timeframes+1] >= low[fractals_timeframes] and low[fractals_timeframes+2] >= low[fractals_timeframes] and low[fractals_timeframes+idx + 2] > low[fractals_timeframes])
    down_flag_up_frontier_3 := down_flag_up_frontier_3 and (low[fractals_timeframes+1] >= low[fractals_timeframes] and low[fractals_timeframes+2] >= low[fractals_timeframes] and low[fractals_timeframes+3] >= low[fractals_timeframes] and low[fractals_timeframes+idx + 3] > low[fractals_timeframes])
    down_flag_up_frontier_4 := down_flag_up_frontier_4 and (low[fractals_timeframes+1] >= low[fractals_timeframes] and low[fractals_timeframes+2] >= low[fractals_timeframes] and low[fractals_timeframes+3] >= low[fractals_timeframes] and low[fractals_timeframes+4] >= low[fractals_timeframes] and low[fractals_timeframes+idx + 4] > low[fractals_timeframes])

bool flag_down_frontier = down_flag_up_frontier_0 or down_flag_up_frontier_1 or down_flag_up_frontier_2 or down_flag_up_frontier_3 or down_flag_up_frontier_4
bool down_fractal = down_flag_down_frontier and flag_down_frontier

plotshape(down_fractal, title='Williams Fractals Down', style=shape.arrowdown, location=location.belowbar, offset=-fractals_timeframes, color=red_color, size=size.small, display=display.pane)
plotshape(up_fractal, title='Williams Fractals Up', style=shape.arrowup, location=location.abovebar, offset=-fractals_timeframes, color=green_color, size=size.small, display=display.pane)
