// @version=6
indicator(title = "EMAs", shorttitle = "EMAs", overlay = true)


//-----------------------------------------------------------------------------*
//  Constants
//-----------------------------------------------------------------------------{
color TRANSPARENT_COLOR = color.new(#000000, 100)
color RED_COLOR = #B3123B
color GREEN_COLOR = #12B3A7
color YELLOW_COLOR = #B38812
color AQUA_COLOR = #128AB3


//-----------------------------------------------------------------------------*
// Settings
//-----------------------------------------------------------------------------{
src = input.source(close, title = "Source")
ema1Len = input.int(9, title = "EMA 1")
ema2Len = input.int(21, title = "EMA 2")
ema3Len = input.int(50, title = "EMA 3")
ema4Len = input.int(200, title = "EMA 4")


//-----------------------------------------------------------------------------*
// Value
//-----------------------------------------------------------------------------{
ema1 = ta.ema(src, ema1Len)
ema2 = ta.ema(src, ema2Len)
ema3 = ta.ema(src, ema3Len)
ema4 = ta.ema(src, ema4Len)


//-----------------------------------------------------------------------------*
// Plots
//-----------------------------------------------------------------------------{
plot(ema1, color = GREEN_COLOR, linewidth = 1, display = display.pane)
plot(ema2, color = RED_COLOR, linewidth = 1, display = display.pane)
plot(ema3, color = YELLOW_COLOR, linewidth = 1, display = display.pane)
plot(ema4, color = AQUA_COLOR, linewidth = 1, display = display.pane)
