// © tamth_

// @version=5
indicator(title = "Ichimoku Kinko Hyo", shorttitle = "Ichimoku", overlay = true)

//-----------------------------------------------------------------------------{
// Constants
//-----------------------------------------------------------------------------{
color TRANSPARENT_COLOR = #ffffff00
color RED_COLOR = #e91e62
color AQUA_COLOR = #00bbf9
color LIGHT_GRAY_COLOR = #364156
color DARK_GRAY_COLOR = #212d40
color PURPLE_COLOR = #764AF1


//------------------------------------------------------------------------------
// Settings
//-----------------------------------------------------------------------------{
int tenkanLen = input.int(9, minval = 1, title = "Tenkan-Sen Length")
int kijunLen = input.int(26, minval = 1, title = "Kijun-Sen Length")
int senkouSpanBLen = input.int(52, minval = 1, title = "Senkou-Span B Length")
int chikouSpanDisplacement = input.int(26, minval = 1, title = "Chikou-Span Displacement")
int kumoCloudDisplacement = input.int(26, minval = 1, title = "Kumo Cloud Displacement")


//------------------------------------------------------------------------------
// Get lines' value
//-----------------------------------------------------------------------------{
getDonchian(len) => math.avg(ta.lowest(len), ta.highest(len))

tenkan = getDonchian(tenkanLen)
kijun = getDonchian(kijunLen)
senkouSpanA = math.avg(tenkan, kijun)
senkouSpanB = getDonchian(senkouSpanBLen)


//------------------------------------------------------------------------------
// Set lines and kumo cloud
//-----------------------------------------------------------------------------{
plot(tenkan, color = AQUA_COLOR, title = "Tenkan-Sen")
plot(kijun, color = RED_COLOR, title = "Kijun-Sen")
plot(close, offset = -chikouSpanDisplacement + 1, color = PURPLE_COLOR, title = "Chikou-Span")
senkouSpanAPlot = plot(senkouSpanA, offset = kumoCloudDisplacement - 1, color = LIGHT_GRAY_COLOR, title = "Senkou-Span A")
senkouSpanBPlot = plot(senkouSpanB, offset = kumoCloudDisplacement - 1, color = LIGHT_GRAY_COLOR, title = "Senkou-Span B")
fill(senkouSpanAPlot, senkouSpanBPlot, color = senkouSpanA > senkouSpanB ? color.new(DARK_GRAY_COLOR, 80) : color.new(LIGHT_GRAY_COLOR, 60))