// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © tamth_

//@version=6
indicator("KAMAs", overlay = true)

src = input.source(close, title="Source")
length = input.int(21, title="Length")
fastLength = input.int(2, title="Fast EMA Length")
slowLength = input.int(30, title="Slow EMA Length")
htf     = input.timeframe("", title="Higher Timeframe")


calcKAMA() =>
    mom = math.abs(ta.change(src, length))
    volatility = math.sum(math.abs(ta.change(src)), length)
    efficiencyRatio = volatility != 0 ? mom / volatility : 0
    fastAlpha = 2 / (fastLength + 1)
    slowAlpha = 2 / (slowLength + 1)
    alpha = math.pow(efficiencyRatio * (fastAlpha - slowAlpha) + slowAlpha, 2)
    kama = 0.0
    kama := alpha * src + (1 - alpha) * nz(kama[1], src)


kama = calcKAMA()
htfKama = request.security(syminfo.tickerid, htf, calcKAMA())


plot(kama, title="KAMA", linewidth=1, color=color.blue)
plot(htfKama, title="HTF KAMA", linewidth=1, color=color.orange)