// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © tamth_

//@version=6
indicator("RSI", overlay = false, max_boxes_count = 500, max_lines_count = 500, max_labels_count = 500, max_bars_back = 5000)

//-----------------------------------------------------------------------------
// Constants
//-----------------------------------------------------------------------------
// Colors
color TRANSPARENT_COLOR = #ffffff00
color AQUA_COLOR        = #4CC9F0
color BLUE_COLOR        = #4361ee
color PURPLE_COLOR      = #3F37C9
color LIGHT_GRAY_COLOR  = #364156

//-----------------------------------------------------------------------------
// Settings
//-----------------------------------------------------------------------------
domcycle     = input.int(21, minval = 10, title = "Length")
src          = close
crsi         = 0.0
cyclelen     = domcycle / 2
vibration    = 10
leveling     = 10.0
cyclicmemory = domcycle * 2

//-----------------------------------------------------------------------------
// Calculations
//-----------------------------------------------------------------------------
torque     = 2.0 / (vibration + 1)
phasingLag = (vibration - 1) / 2.0

up   = ta.rma(math.max(ta.change(src), 0), cyclelen)
down = ta.rma(-math.min(ta.change(src), 0), cyclelen)

rsi = down == 0 ? 100 : up == 0 ? 0 : 100 - 100 / (1 + up / down)

crsi := torque * (2 * rsi - rsi[phasingLag]) + (1 - torque) * nz(crsi[1])

lmax = -999999.0
lmin = 999999.0

for i = 0 to cyclicmemory - 1 by 1
    if nz(crsi[i], -999999.0) > lmax
        lmax := nz(crsi[i])
        lmax
    else
        if nz(crsi[i], 999999.0) < lmin
            lmin := nz(crsi[i])
            lmin

mstep = (lmax - lmin) / 100
aperc = leveling / 100

db = 0.0
for steps = 0 to 100 by 1
    testvalue = lmin + mstep * steps
    above     = 0
    below     = 0

    for m = 0 to cyclicmemory - 1 by 1
        below := below + (crsi[m] < testvalue ? 1 : 0)
        below

    ratio = below / cyclicmemory

    if ratio >= aperc
        db := testvalue
        break
    else
        continue

ub = 0.0
for steps = 0 to 100 by 1
    testvalue = lmax - mstep * steps
    above     = 0

    for m = 0 to cyclicmemory - 1 by 1
        above := above + (crsi[m] >= testvalue ? 1 : 0)
        above

    ratio = above / cyclicmemory

    if ratio >= aperc
        ub := testvalue
        break
    else
        continue

//-----------------------------------------------------------------------------
// Render
//-----------------------------------------------------------------------------
hline(30, color = color.new(LIGHT_GRAY_COLOR, 50), linestyle = hline.style_dashed)
hline(50, color = color.new(LIGHT_GRAY_COLOR, 30), linestyle = hline.style_dashed)
hline(70, color = color.new(LIGHT_GRAY_COLOR, 50), linestyle = hline.style_dashed)

lowband  = plot(db, "Low Band", color = PURPLE_COLOR, display = display.pane)
highband = plot(ub, "High Band", color = PURPLE_COLOR, display = display.pane)
plot(crsi, "RSI", AQUA_COLOR, display = display.pane)

//-----------------------------------------------------------------------------
