// © tamth_
// @version=5
indicator("Market Cipher B", overlay = false)


int overbought = input.int(60, title = "Overbought")
int oversold = input.int(-60, title = "Oversold")


method get_waves_and_vwap(series float src, int chl_len, int avg_len) =>
    float esa = ta.ema(src, chl_len)
    float d = ta.ema(math.abs(src - esa), chl_len)
    float ci = (src - esa) / (0.015 * d)
    float leading_wave = ta.ema(ci, avg_len)
    float lagging_wave = ta.sma(leading_wave, 3)
    float vwap = leading_wave - lagging_wave
    [leading_wave, lagging_wave, vwap]

method get_money_flow(int period, int mult, float y) => ta.sma(((close - open) / (high - low)) * mult, period) - y

get_expression() =>
    int offset = 0
    [leading_wave, lagging_wave, vwap] = get_waves_and_vwap(hlc3, 9, 12)
    // float moneyflow = get_money_flow(60, 200, 2.25)
    float moneyflow = get_money_flow(50, 100, 0)
    float rsi = ta.sma(ta.stoch(close, high, low, 40), 2)
    float stoch_rsi = ta.sma(ta.stoch(close, high, low, 81), 2)
    [leading_wave[offset], lagging_wave[offset], vwap[offset], moneyflow[offset], rsi[offset], stoch_rsi[offset]]

[leading_wave, lagging_wave, vwap, moneyflow, rsi, stoch_rsi] = request.security(syminfo.tickerid, timeframe.period, get_expression())


plot(overbought, title = "Overbought", color = color.new(color.white, 80), display = display.pane)
plot(oversold, title = "Oversold", color = color.new(color.white, 80), display = display.pane)
plot(leading_wave, title = "Leading Wave", color = #90c6f2, linewidth = 1, style = plot.style_area)
plot(lagging_wave, title = "Lagging Wave", color = color.new(#1a54a7, 10), linewidth = 1, style = plot.style_area)
plot(vwap, title = "VWAP", color = color.new(color.yellow, 30), linewidth = 1, style = plot.style_area)
plot(moneyflow, title = "Money Flow", color = moneyflow > 0 ? color.new(#39b071, 40) : color.new(#d94c5d, 40), linewidth = 2, style = plot.style_area)
plot(ta.crossover(leading_wave, lagging_wave) ? lagging_wave : na, title = "Buy Signal", color = color.new(#39b071, 20), linewidth = 3, style = plot.style_circles, display = display.pane)
plot(ta.crossunder(leading_wave, lagging_wave) ? lagging_wave : na, title = "Sell Signal", color = color.new(#d94c5d, 20), linewidth = 3, style = plot.style_circles, display = display.pane)
plot(0, title = "Zero", color = color.white, display = display.pane)
plot(rsi, title = "Rsi", color = #e52be6)
plot(stoch_rsi, title = "Stoch Rsi", color = rsi > stoch_rsi ? #39b071 : #d94c5d, linewidth = 2)
var p0 = plot(-100, title = "Money Flow Annotation", color = color.new(color.white, 100), editable = false, display = display.pane)
var p1 = plot(-105, title = "Money Flow Annotation", color = color.new(color.white, 100), editable = false, display = display.pane)
fill(p0, p1, title = "Money Flow Annotation", color = moneyflow > 0 ? color.new(#39b071, 20) : color.new(#d94c5d, 20))
plotshape(ta.crossover(leading_wave, lagging_wave) and leading_wave < oversold, title = "Strong Buy Signal", style = shape.xcross, location = location.bottom, color = #39b071, size = size.tiny, display = display.pane)